//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportMusic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Intensiv2018Entities : DbContext
    {
        public Intensiv2018Entities()
            : base("name=Intensiv2018Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Edit_Playlist> Edit_Playlist { get; set; }
        public virtual DbSet<Edit_Track> Edit_Track { get; set; }
        public virtual DbSet<Edit_User> Edit_User { get; set; }
        public virtual DbSet<Playlist> Playlist { get; set; }
        public virtual DbSet<User_Track> User_Track { get; set; }
        public virtual DbSet<User_Playlist> User_Playlist { get; set; }
        public virtual DbSet<Track> Tracks1 { get; set; }
        public virtual DbSet<User_Track_Playlist> User_Track_Playlist { get; set; }
        public virtual DbSet<SysUser> SysUsers { get; set; }
    }
}
