//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportMusic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.User_Track_Playlist = new HashSet<User_Track_Playlist>();
        }
    
        public int id { get; set; }
        public int downloader { get; set; }
        public string artist { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public string mood { get; set; }
        public Nullable<int> bitrate { get; set; }
        public string source { get; set; }
        public string path { get; set; }
        public System.TimeSpan duration { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Track_Playlist> User_Track_Playlist { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
